CREATE TABLE [dbo].[AppLogs]
(
	[Id] INT NOT NULL IDENTITY,
	[Method] NVARCHAR(255) NOT NULL,
	[Error] NVARCHAR(MAX) NOT NULL,
	[Date] DATETIME NOT NULL DEFAULT GETDATE()

	CONSTRAINT PK_APPLOGS_ID PRIMARY KEY ([Id])
)
