CREATE TABLE [dbo].[Users]
(
	[Id] INT NOT NULL IDENTITY,
	[Email] NVARCHAR(255) NOT NULL,
	[Pwd] BINARY(64) NOT NULL,
	[FirstName] NVARCHAR(255) NOT NULL,
	[LastName] NVARCHAR(255) NOT NULL,
	[City] NVARCHAR(255) NOT NULL,
	[Perms] NVARCHAR (20) NOT NULL DEFAULT 'User',
	[Created] DATETIME NOT NULL DEFAULT GETDATE(),
	[Updated] DATETIME NOT NULL DEFAULT GETDATE(),
	[IsActive] BIT NOT NULL DEFAULT 1,
	[IsBan] BIT NOT NULL DEFAULT 0

	CONSTRAINT PK_USERS_ID PRIMARY KEY ([Id]),
	CONSTRAINT UNIQUE_USERS_EMAIL UNIQUE ([Email])
)
