CREATE TABLE [dbo].[Users]
(
	[Id] INT NOT NULL IDENTITY,
	[Email] NVARCHAR(255) NOT NULL,
	[Pwd] BINARY(64) NOT NULL,
	[Perms] NVARCHAR (20) NOT NULL DEFAULT 'User',
	[Created] DATETIME NOT NULL DEFAULT GETDATE(),
	[Updated] DATETIME NOT NULL DEFAULT GETDATE(),
	[Deactivated] BIT NOT NULL DEFAULT 0

	CONSTRAINT PK_USERS_ID PRIMARY KEY ([Id]),
	CONSTRAINT UNIQUE_USERS_EMAIL UNIQUE ([Email])
)
